### ISSUE TITLE
ConfigMaker (develop) Error on Run

### ISSUE THREAD

**Issue by ghost** [HoraceAndTheSpider/UAEConfigMaker#38]
Hi, been away for a few days. I tried your latest config maker but got this error -

```
Config Save Path: /home/pi/RetroPie/roms/amiga/
Games Files Path: Games_WHDLoad_HDF

Traceback (most recent call last):
  File "uae_config_maker.py", line 1384, in <module>
    do_scan_base(inputdir,outputdir)
  File "uae_config_maker.py", line 1173, in do_scan_base
    do_scan(inputdir, this_line, outputdir)
  File "uae_config_maker.py", line 195, in do_scan
    for file in glob.iglob(input_directory + pathname + '/**/*.*', recursive=True):
TypeError: iglob() got an unexpected keyword argument 'recursive'
```
As you know, i'm using HDF Data Only.
Games_WHDLoad_HDF
Games_WHDLoad_HDF_AGA

**Comment by HoraceAndTheSpider** [comment]
Looks like your version of Python3 is not able to use the recursive argument. If possible please can you check what version number is returned.

If so, this may only be supported on Python 3.5 +. I will implement a fix to work with python 3.0-3.4 , or at worst a warning that Python needs updating on the host machine.

**Comment by ghost** [comment]
Could you tell me how to find the version number ? I'm using RetroPie.

**Comment by HoraceAndTheSpider** [comment]
i think this should be `python3 -V` from command line

**Comment by ghost** [comment]
Python 3.4.2

**Comment by HoraceAndTheSpider** [comment]
`sudo apt-get install python3` might work, or at least it should tell you what you need to type to update it. 

I will need to establish whether 3.4 is the standard on RetroPie though, given that it is quite out of date

**Comment by ghost** [comment]
It says 'Python3 is already the newest version' !

**Comment by HoraceAndTheSpider** [comment]
Fix applied - This should be Python 3.4 compatible now.
